using ServiceReference;
using System.ServiceModel;

Console.WriteLine("SOAP client started...");

var binding = new BasicHttpBinding();
var endpoint = new EndpointAddress("http://localhost:5062/MathService.svc");

// This class is generated by dotnet-svcutil
var client = new MathServiceClient(binding, endpoint);

int a = 15;
int b = 25;

int result = await client.AddAsync(a, b);
Console.WriteLine($"Result: {a} + {b} = {result}");

try
{
    int resultError = await client.AddWithErrorAsync(a, b);
    Console.WriteLine($"Result: {a} + {b} = {result}");
}
catch (Exception ex)
{
    Console.WriteLine("SOAP Fault:");
    Console.WriteLine(ex);
}

await client.CloseAsync();
Console.WriteLine("Done.");