//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public string Role { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
