UserParameter=asp.cpu_load,curl -s http://host.docker.internal:5000/metrics | jq .cpu_load
UserParameter=asp.requests,curl -s http://host.docker.internal:5000/metrics | jq .requests
UserParameter=asp.delta,curl -s http://host.docker.internal:5000/metrics | jq .delta