config setup
    charondebug="all"

conn server-tunnel
    auto=start
    type=tunnel

    keyexchange=ikev2
    authby=psk

    left=XX.XX.XX.109
    leftsubnet=XX.XX.XX.109/32

    right=XX.XX.XX.204
    rightsubnet=XX.XX.XX.204/32

    ike=aes256-sha256-modp2048
    esp=aes256-sha256

    keyingtries=%forever
    ikelifetime=60m
    lifetime=20m