version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "6831:6831"
      - "4318:4318" # Открыть порт 4318
    volumes:
      - ./otlp-config.yaml:/etc/jaeger/config.yaml
      - jaeger-data:/data

volumes:
  jaeger-data: