services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prom_meter
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped