receivers:
  otlp:
    protocols:
      http:
        endpoint: :4318
      grpc:
        endpoint: :4317

processors:
  batch:
    timeout: 1s

exporters:
  prometheus:
    endpoint: ":9090"

extensions:
  health_check:
  
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]