apiVersion: batch/v1
kind: CronJob

metadata:
  name: postgres-backup

spec:
  timeZone: "Europe/Berlin"
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 600
      ttlSecondsAfterFinished: 3600

      completions: 5
      parallelism: 2

      template:
        spec:
          restartPolicy: Never

          containers:
            - name: backup
              image: worker:1.0

              command:
                - /bin/sh
                - -c
                - pg_dump mydb > /backup/db.sql