receivers:
  zipkin:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

extensions:
  health_check:
  
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [zipkin, otlp]
      processors: [batch]
      exporters: [zipkin]