@startuml
title Оформление заказа

|Покупатель|

start

:Добавить товар в корзину;
:Оформить заказ;

|Магазин|

:Проверить наличие товара;

if (Товар есть?) then (Да)

    :Создать заказ;

else (Нет)

    :Сообщить "Нет в наличии";
    stop

endif

' Параллельные потоки
fork

    |Платёжный сервис|

    :Провести оплату;

    if (Оплата успешна?) then (Да)
        :Подтвердить оплату;
    else (Нет)
        :Отправить отказ;

        ' Завершаем только эту ветку
        kill
    endif

fork again

    |Магазин|

    :Зарезервировать товар;

fork again

    |Сервис уведомлений|

    :Отправить Email;

end fork

|Магазин|

:Отправить событие\n<<send signal>> OrderCreated;

|Склад|

:Получить событие\n<<accept event>> OrderCreated;

:Начать сборку заказа;

stop

@enduml